name: CI - Windows
on: [pull_request, push]

jobs:
  build:
    name: 🚧Build
    runs-on: windows-latest

    env:
      prog_name: Examples/Triangle/main.exe

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Configure build for amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Install build tools
        run: |
          choco install ninja

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            C:/vcpkg
            !C:/vcpkg/buildtrees
          key: ${{ runner.os }}-${{ hashFiles('.github/workflows/commands.ps1') }}

      - name: Install dependencies
        run: |
          pwsh .github/workflows/installation.ps1

      - name: '🚧 Build package'
        run: |
          pwsh .github/workflows/commands.ps1
          New-Item -Type Directory build/dist
          Copy-Item build/${{env.prog_name}} build/dist/
          Copy-Item -Recurse Examples/Triangle/Shaders build/dist/

      - name: '📤 upload package'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/dist
